### ISSUE TITLE
Deploying aldryn_video after installation with Aldryn Dashboard fails

### ISSUE THREAD

**Issue by MarcMueltin** [aldryn/aldryn-video#15]
When deploying the newly installed aldryn_video addon via the Aldryn Dashboard and try to deploy the changes, then the build fails. This is the end of the very long docker log:

[91mTraceback (most recent call last):
  File "manage.py", line 7, in <module>
    startup.manage(path=os.path.dirname(os.path.abspath(__file__)))
  File "/virtualenv/lib/python2.7/site-packages/aldryn_django/startup.py", line 11, in manage
    utility.execute()
  File "/virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
[0m[91m    django.setup()
  File "/virtualenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/virtualenv/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/virtualenv/lib/python2.7/site-packages/cms/apps.py", line 12, in ready
    setup()
  File "/virtualenv/lib/python2.7/site-packages/cms/utils/setup.py", line 65, in setup
    plugin_pool.validate_templates()
  File "/virtualenv/lib/python2.7/site-packages/cms/plugin_pool.py", line 82, in validate_templates
    % (plugin, template)
django.core.exceptions.ImproperlyConfigured: CMS Plugins must define a render template (<class 'aldryn_video.cms_plugins.OEmbedVideoPlugin'>) that exists: aldryn_video/video.html
[0m

**Comment by FinalAngel** [comment]
Will be fixed with https://github.com/aldryn/aldryn-video/pull/16
